Repository tambercore/mud, pull requests merged in 2025-02, with the labels that each got.

#58 55 fix issues with dependent function types
  src/ccg/node.rs
  src/lambda/dependent_function.rs
  src/lambda/reducible.rs
  src/lambda/types.rs
  src/main.rs
  src/monty/lambda_generation.rs
  src/monty/test_expression_generation.rs
Labels: bug

#61 55 fix issues with dependent function types
  data/universal_quantifiers.txt
  src/ccg/node.rs
  src/lingo/mod.rs
  src/lingo/quantifiers.rs
  src/main.rs
  src/monty/lambda_generation.rs
  src/wordnet/interface.rs
  src/wordnet/wordnode.rs
Labels: bug, feature

#67 62 handle existential quantification with σ types
  Cargo.toml
  data/existential_quantifiers.txt
  src/ccg/node.rs
  src/ccg/tag_insertion.rs
  src/lambda/dependent_function.rs
  src/lambda/dependent_sum.rs
  src/lambda/macros.rs
  src/lambda/mod.rs
  src/lambda/reducible.rs
  src/lambda/types.rs
  src/lingo/quantifiers.rs
  src/main.rs
  src/monty/lambda_generation.rs
Labels: bug

#70 69 handle quantifiers of quantifiers
  src/ccg/node.rs
  src/ccg/tag_insertion.rs
  src/lambda/abstraction.rs
  src/lambda/dependent_function.rs
  src/lambda/dependent_sum.rs
  src/lambda/macros.rs
  src/lambda/reducible.rs
  src/main.rs
  src/monty/lambda_generation.rs
Labels: bug

#74 Add typing context
  data/existential_quantifiers.txt
  src/lambda/dependent_function.rs
  src/lambda/dependent_sum.rs
  src/lambda/macros.rs
  src/lambda/types.rs
  src/main.rs
  src/monty/lambda_generation.rs
  src/monty/mod.rs
  src/monty/test_expression_generation.rs
  src/monty/test_predicate_expansion.rs
  src/monty/typing_context.rs
Labels: feature

#80 add: uncomment two lines
  src/lambda/types.rs
  src/main.rs
Labels: feature

#86 85 Introduce Conjunction (v1)
  src/composer/agdaify.rs
  src/composer/case_converter.rs
  src/composer/lambda_to_types.rs
  src/composer/mod.rs
  src/composer/postulate.rs
  src/main.rs
Labels: feature
